/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class input_messages {
    getFieldTypeMap() {
        let fieldTypeMap = new Map();
        fieldTypeMap.set('id', 'String');
        fieldTypeMap.set('text', 'String');
        fieldTypeMap.set('type', 'Integer');
        fieldTypeMap.set('user_id', 'String');
        return fieldTypeMap;
    }

    getClassName() {
        return 'input_messages';
    }

    getPrimaryKeyList() {
        let primaryKeyList = [];
        primaryKeyList.push('id');
        return primaryKeyList;
    }

    getIndexList() {
        let indexList = [];
        return indexList;
    }

    getEncryptedFieldList() {
        let encryptedFieldList = [];
        return encryptedFieldList;
    }

    setId(id) {
        this.id = id;
    }

    getId() {
        return this.id;
    }

    setText(text) {
        this.text = text;
    }

    getText() {
        return this.text;
    }

    setType(type) {
        this.type = type;
    }

    getType() {
        return this.type;
    }

    setUser_id(user_id) {
        this.user_id = user_id;
    }

    getUser_id() {
        return this.user_id;
    }
}

module.exports = {input_messages}