/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class full_messages {
    getFieldTypeMap() {
        let fieldTypeMap = new Map();
        fieldTypeMap.set('id', 'String');
        fieldTypeMap.set('text', 'String');
        fieldTypeMap.set('type', 'Integer');
        fieldTypeMap.set('nickname', 'String');
        fieldTypeMap.set('email', 'String');
        fieldTypeMap.set('phone_number', 'String');
        fieldTypeMap.set('picture_url', 'String');
        fieldTypeMap.set('color', 'String');
        fieldTypeMap.set('credential_provider_id', 'String');
        fieldTypeMap.set('date_ins', 'Date');
        fieldTypeMap.set('user_id', 'String');
        return fieldTypeMap;
    }

    getClassName() {
        return 'full_messages';
    }

    getPrimaryKeyList() {
        let primaryKeyList = [];
        primaryKeyList.push('id');
        return primaryKeyList;
    }

    getIndexList() {
        let indexList = [];
        return indexList;
    }

    getEncryptedFieldList() {
        let encryptedFieldList = [];
        return encryptedFieldList;
    }

    setId(id) {
        this.id = id;
    }

    getId() {
        return this.id;
    }

    setText(text) {
        this.text = text;
    }

    getText() {
        return this.text;
    }

    setType(type) {
        this.type = type;
    }

    getType() {
        return this.type;
    }

    setNickname(nickname) {
        this.nickname = nickname;
    }

    getNickname() {
        return this.nickname;
    }

    setEmail(email) {
        this.email = email;
    }

    getEmail() {
        return this.email;
    }

    setPhone_number(phone_number) {
        this.phone_number = phone_number;
    }

    getPhone_number() {
        return this.phone_number;
    }

    setPicture_url(picture_url) {
        this.picture_url = picture_url;
    }

    getPicture_url() {
        return this.picture_url;
    }

    setColor(color) {
        this.color = color;
    }

    getColor() {
        return this.color;
    }

    setCredential_provider_id(credential_provider_id) {
        this.credential_provider_id = credential_provider_id;
    }

    getCredential_provider_id() {
        return this.credential_provider_id;
    }

    setDate_ins(date_ins) {
        this.date_ins = date_ins;
    }

    getDate_ins() {
        return this.date_ins;
    }

    setUser_id(user_id) {
        this.user_id = user_id;
    }

    getUser_id() {
        return this.user_id;
    }
}

module.exports = {full_messages}